/*
 * Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
 * 2^2 = 4, 2^3 = 8, 2^4 = 16, 2^5 = 32
 * 3^2 = 9, 3^3 = 27, 3^4 = 81, 3^5 = 243
 * 4^2 = 16, 4^3 = 64, 4^4 = 256, 4^5 = 1024
 * 5^2 = 25, 5^3 = 125, 5^4 = 625, 5^5 = 3125
 * If they are then placed in numerical order, with any repeats removed, we get
 * the following sequence of 15 distinct terms:
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <=
 * 100 and 2 <= b <= 100?
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

#define LOWER_LIMIT 2
#define UPPER_LIMIT 100

int compare(const void *a, const void *b);
void power(int a, int b, char **str, int numDigits);

int main() {
    int i, a, b;
    double maxNumber = pow(UPPER_LIMIT, UPPER_LIMIT);
    int maxDigits = log10(maxNumber) + 1;
    int totalTerms = (UPPER_LIMIT + 1) * (UPPER_LIMIT + 1);

    // Terms are stored in a 1D array (for easier sorting later)
    // terms[i] is equal to a^b where a and b are defined as below
    char **terms = (char **) malloc(totalTerms * sizeof(char *));
    for (i = 0; i < totalTerms; i++) {
        terms[i] = (char *) malloc(maxDigits * sizeof(char));
        
        a = i / (UPPER_LIMIT+1);
        b = i % (UPPER_LIMIT+1);

        // If a or b are not in the given bounds, we just let terms[i] = "N/A"
        if ((a >= 2 && a <= UPPER_LIMIT) && (b >= 2 && b <= UPPER_LIMIT))
            power(a, b, &(terms[i]), maxDigits);
        else 
            strcpy(terms[i], "N/A");
    }

    // Sort the array of terms
    qsort(terms, totalTerms, sizeof(char *), compare);

    // Count the number of distinct terms by comparing the current term with the
    // next term (since the array is sorted); exclude "N/A" terms
    int counter = 0;
    for (i = 0; i < totalTerms - 1; i++) {
        if (strcmp(terms[i], "N/A") != 0) {
            if (strcmp(terms[i], terms[i+1]) != 0)
                counter++;
        }
    }

    printf("%d\n", counter);
}

int compare(const void *a, const void *b) {
    char * const *strA = a;
    char * const *strB = b;
    return strcmp(*strA, *strB);
}

void power(int a, int b, char **str, int numDigits) {
    int i, j, carryOver, value;
    char buffer[3];
    
    // Let str represent the value 1
    for (i = 0; i < numDigits-1; i++)
        (*str)[i] = '0';
    (*str)[numDigits-1] = '1';
    
    // Multiply 'a' with the str value ('b' number of times)
    for (i = 0; i < b; i++) {
        carryOver = 0;
        for (j = numDigits-1; j >= 0; j--) {
            value = a * ((*str)[j]-'0') + carryOver;
            sprintf(buffer, "%03d", value);
            carryOver = 10*(buffer[0]-'0') + (buffer[1]-'0');
            (*str)[j] = buffer[2];
        }
    }
}
